# Data Analysis

방대한 양의 데이터를 수집, 분석, 시각화 처리를 통해 유의미한 정보를 추출
파이썬 패키지로는 numpy, pandas, matplotlib, seaborn 등이 주로 사용되고 있다.

# Numpy
Numerical Python 대규모의 다차원 배열, 수치연산을 지원하는 라이브러리

In [11]:
# !명령어를 통해 cmd 실행도 가능
!conda install numpy

^C


## 다차원 배열 생성

In [2]:
import numpy as np

In [8]:
arr = np.array([1, 2, 3, 4, 5])
print(arr, type(arr))
lst = [1, 2, 3, 4, 5]
print(lst, type(lst))

[1 2 3 4 5] <class 'numpy.ndarray'>
[1, 2, 3, 4, 5] <class 'list'>


In [9]:
arr = np.array((10, 20, 30))
print(arr, type(arr))

[10 20 30] <class 'numpy.ndarray'>


In [18]:
# ndarray 구조 확인
arr = np.array([1, 2, 3])
print(arr)
arr.shape, arr.ndim, arr.size, arr.dtype
# 형태, 깊이 - 차원 수(1차원이므로 1차 튜플), 요소개수, 요소자료형
# cell의 마지막줄은 자동으로 출력

[1 2 3]


((3,), 1, 3, dtype('int64'))

In [22]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)
print([1, 2, 3], [4, 5, 6]) #파이썬 리스트
# 대괄호가 두개면 2차원
arr_2d.shape, arr_2d.ndim, arr_2d.size, arr_2d.dtype
# 배열은 오직 한가지 자료 형태만 저장 가능

[[1 2 3]
 [4 5 6]]
[1, 2, 3] [4, 5, 6]


((2, 3), 2, 6, dtype('int64'))

In [29]:
# ndarray 자료형
arr_int = np.array([1, 2, 3])
print(arr_int.dtype) #int64(8byte), int32(4byte)

arr_float = np.array([1.234, 3.456, 9.876, 10])  #ndarray는 하나의 타입만 저장가능
print(arr_float.dtype)

arr_bool = np.array([True, False, True, False])
print(arr_bool.dtype)

arr_str = np.array(['Hello', 'World', 'numpy', 'Good!'])
print(arr_str.dtype) # 유니코드, 가장 긴 개수 반환

int64
float64
bool
<U20


In [35]:
# 형변환
arr = np.array([1.23, 3.5, 7, 9]) # int, float이 섞여있다면, 모두 저장 가능한 float으로 변환저장

arr = np.array([1.23, 3.5, 7, 9], dtype=float)
arr = np.array([1.23, 3.5, 7, 9], dtype=int) # 실수는 소수점이하 버림

arr = np.array([1.23, 3.5, 7, 9])
arr = arr.astype(int)
print(arr)

arr, arr.dtype

[1 3 7 9]


(array([1, 3, 7, 9]), dtype('int64'))

In [1]:
# python의 list | ndarray 차이
# - ndarray는 동일한 자료형만 저장 가능
# - 다차원인 경우, 중첩배열은 동일한 크기만 허용
# - 형태/길이를 확인하는 방법 len() | ndarray.shape, ndarray.ndim, ndarray.size

lst = [1, 2, 3, 'hello']
lst = [[1, 2, 3], [4, 5, 6]]
lst, len(lst), len(lst[0]), len(lst[1])

([[1, 2, 3], [4, 5, 6]], 2, 3, 3)

In [51]:
arr = np.array([1, 2, 3, 'hello']) # string 형태로 들어가 버림
# arr = np.array([[1, 2, 3], [4, 5]]) # ValueError
arr, arr.shape, arr.ndim, arr.size

(array(['1', '2', '3', 'hello'], dtype='<U21'), (4,), 1, 4)

In [67]:
# 0, 1, 특정수로 초기화된 ndarray 생성하기
arr = np.zeros((2, 3))
print(arr)

# arr = np.zeros((2, 3, 4))
# print(arr)

arr = np.ones((3, 2))
print(arr)

arr = np.full((4, 1), 8)
print(arr)
arr = np.full((1, 4), 8)
print(arr)
arr = np.full((4,), 8)
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[8]
 [8]
 [8]
 [8]]
[[8 8 8 8]]
[8 8 8 8]


In [74]:
# shape을 따라 만들기
# - np.zeros_like(ndarray)
# - np.ones_like(ndarray)
# - np.full_like(ndarray, n)

arr = np.array([[2, 3], [4, 5]])
print(arr, arr.shape)

arr_0 = np.zeros_like(arr)
print(arr_0)

arr_1 = np.ones_like(arr)
print(arr_1)

arr_7 = np.full_like(arr, 7)
print(arr_7)

[[2 3]
 [4 5]] (2, 2)
[[0 0]
 [0 0]]
[[1 1]
 [1 1]]
[[7 7]
 [7 7]]


In [78]:
# 수열 생성 np.arange(start, stop, step)
arr = np.arange(1, 11) # start포함, stop미포함
print(arr)

arr = np.arange(1, 11, 2)
print(arr)

arr = np.arange(10) # 0이상 end값 미만
print(arr)

arr = np.arange(1, 10, .1)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]
[0 1 2 3 4 5 6 7 8 9]
[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7
 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5 3.6 3.7 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5
 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3 5.4 5.5 5.6 5.7 5.8 5.9 6.  6.1 6.2 6.3
 6.4 6.5 6.6 6.7 6.8 6.9 7.  7.1 7.2 7.3 7.4 7.5 7.6 7.7 7.8 7.9 8.  8.1
 8.2 8.3 8.4 8.5 8.6 8.7 8.8 8.9 9.  9.1 9.2 9.3 9.4 9.5 9.6 9.7 9.8 9.9]


In [82]:
# 수열 생성 np.linspace(start, stop, num)
# - stop 포함
# - num은 요소 개수
arr = np.linspace(0, 10, 5) # 0에서 10사이의 균일한 간격으로 숫자 5개
print(arr)

arr = np.linspace(0, 100, 11)
print(arr)

[ 0.   2.5  5.   7.5 10. ]
[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


In [85]:
# 수열 생성 np.logspace(start_exp, end_exp, num, base)
# - start_exp : 시작 지수
# - end_exp : 끝 지수
# - num : 생성할 숫자 갯수
# - base : 밑(기본값 : 10)

print(np.linspace(1, 3, 4))
arr = np.logspace(1, 3, 3)
arr = np.logspace(1, 3, 4)
print(arr)
# start, end가 지수값이고, 지수사이에 동일한 간격의 숫자 num(ex.4개)를 뽑아서 그 결과 거듭제곱 값을 나열한게 로그스페이스다.

[1.         1.66666667 2.33333333 3.        ]
[  10.           46.41588834  215.443469   1000.        ]


## ndarray indexing/slicing

In [7]:
# 1차원 배열의 인덱싱
arr = np.arange(1, 11)
print(arr)

print(arr[2])
print(arr[4])
print(arr[9])
# print(arr[10])
print(arr[-1])
print(arr[-2])

[ 1  2  3  4  5  6  7  8  9 10]
3
5
10
10
9


In [9]:
# 2차원 배열 인덱싱
arr_2d = np.array([[10, 20, 30],
                   [40, 50, 60]])
print(arr_2d.shape)

print(arr_2d)
print('-----------')
print(arr_2d[0])
print('-----------')
print(arr_2d[1])
print('-----------')
print(arr_2d[0][0], arr_2d[0, 0], arr_2d[(0, 0)])
print(arr_2d[1][1], arr_2d[1, 1], arr_2d[(1, 1)])

(2, 3)
[[10 20 30]
 [40 50 60]]
-----------
[10 20 30]
-----------
[40 50 60]
-----------
10 10 10
50 50 50


In [10]:
arr = np.array([[11, 22, 33], [44, 55, 66], [77, 88, 99]])
print(arr)
print(arr[1, 0]) # 44
print(arr[2, 1]) # 88
print(arr[-1, -2]) # 88

[[11 22 33]
 [44 55 66]
 [77 88 99]]
44
88
88


In [25]:
# 1차원 배열의 슬라이싱
# [start:end:step]
arr = np.arange(10)
print(arr)

print(arr[3:8])
print(arr[3:])
print(arr[:8])
print(arr[:-1])
print(arr[::2])
print(arr[::-1]) # step에 음수주면 끝에서부터 역순으로 불러오는 것처럼 가져옴

[0 1 2 3 4 5 6 7 8 9]
[3 4 5 6 7]
[3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7]
[0 1 2 3 4 5 6 7 8]
[0 2 4 6 8]
[9 8 7 6 5 4 3 2 1 0]


In [39]:
# 2차원 배열의 slicing
arr = np.array([
     #0  #1  #2
    [10, 20, 30], #0
    [40, 50, 60], #1
    [70, 80, 90]  #2
])
print(arr)
print('=============')
print(arr[0:2, 1:2])
print('=============')
print(arr[0:2])
print('=============')
print(arr[0:2, :])
print('=============')
print(arr[:, 1:])
print('=============')
print(arr[:-1, :1], arr[:-1, :1].shape)
print('=============')
print(arr[:-1, 0], arr[:-1, 0].shape)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
[[20]
 [50]]
[[10 20 30]
 [40 50 60]]
[[10 20 30]
 [40 50 60]]
[[20 30]
 [50 60]
 [80 90]]
[[10]
 [40]] (2, 1)
[10 40] (2,)


In [42]:
# fancy indexing 1차원 배열
# 배열을 사용해서 기존배열을 필터링 처리
arr = np.arange(5, 31, 5)
print(arr)
print(arr[[1, 3, 4]])
indices = [1, 3, 4]
print(arr[indices])

[ 5 10 15 20 25 30]
[10 20 25]
[10 20 25]


In [48]:
# 2차원 배열 fancy indexing
arr = np.array([
    [5, 10, 15, 20],
    [25, 30, 35, 40],
    [45, 50, 55, 60]
])
print(arr)
print('==============')
print(arr[[0, 1], [1, 2]])
print('==============')
row_indices = [0, 1]
col_indices = [1, 2]
print(arr[row_indices, col_indices])
print('==============')
print(arr[[1, 2, 3], [1, 2]])

[[ 5 10 15 20]
 [25 30 35 40]
 [45 50 55 60]]
[10 35]
[10 35]


IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (2,) 

In [52]:
# slicing, fancy indexing 함께 사용 가능
arr = np.array([
    [5, 10, 15, 20],
    [25, 30, 35, 40],
    [45, 50, 55, 60]
])
print(arr)
print('==============')
print(arr[[0, 2], 2:])
print('==============')
print(arr[::2, [2,3]])
# print(arr[[0, 2], [2:]])

[[ 5 10 15 20]
 [25 30 35 40]
 [45 50 55 60]]
[[15 20]
 [55 60]]
[[15 20]
 [55 60]]


In [55]:
# boolean indexing
arr = np.arange(1, 6)
print(arr)

print(arr[[True, False, True, False, False]])

bools = [True, False, True, False, False]
print(arr[bools])

[1 2 3 4 5]
[1 3]
[1 3]


In [67]:
# boolean indexing 2차원 배열
arr = np.array([
    [3, 6, 9],
    [12, 15, 18],
    [21, 24, 27]
])
print(arr)
print('=========')
print(arr[[True, False, False]])
print('=========')
print(arr[[True, False, False], [False, True, True]])
print('=========')
print(arr[[0, 2], [1, 2]])

[[ 3  6  9]
 [12 15 18]
 [21 24 27]]
[[3 6 9]]
[6 9]
[ 6 27]


In [73]:
print(arr)
print(arr[arr > 10])
arr % 2 == 0

[[ 3  6  9]
 [12 15 18]
 [21 24 27]]
[12 15 18 21 24 27]


array([[False,  True, False],
       [ True, False,  True],
       [False,  True, False]])

In [78]:
# np.all(), np.any()
# - np.all() : ndarray의 모든 요소가 조건을 만족할 때 True 반환
# - np.any() : ndarray의 하나의 요소라도 조건을 만족할 때 True 반환
arr = np.array([10, 20, 30, 40, -50])
is_all_positive = np.all(arr > 0)
if is_all_positive:
    print('모든 수는 양수입니다.')
else:
    print('모든 수는 양수가 아닙니다.')

모든 수는 양수가 아닙니다.


In [79]:
ages = np.array([25, 23, 33, 17, 40])
has_minor = np.any(ages < 20) # True
if has_minor:
    print('출입불가')
else:
    print('환영합니다!')

출입불가


In [81]:
# 여기서 문제!!!
# Q1) 다음 중 합격 점수만 출력하세요 (60점 미만은 불합격)
scores = np.array([88, 77, 60, 35, 59, 100, 89, 96])
passed = scores >= 60
scores[passed]


array([ 88,  77,  60, 100,  89,  96])

In [119]:
# Q2) 월별 판매량이 200개 이상인 제품의 판매량을 선택하라.
sales = np.array([
    [120, 150, 100],
    [80, 90, 110],
    [200, 180, 220],
    [50, 45, 70],
    [300, 320, 310]
])
sales.shape
# product = sales >= 200
# sales[product]
sales[sales >= 200]

array([200, 220, 300, 320, 310])

In [134]:
# Q2-1) 세번째 열의 판매량이 100개 이하인 제품(행)의 첫번째 행과 두번째 행의 판매량을 추출하라
print(sales[:, 2] <= 100)

sales1 = sales[sales[:, 2] <= 100]
result = sales1[:, :2][sales1[:, :2] <= 100]
result




[ True False False  True False]


array([50, 45])

In [135]:
# Q2-2) 두번째 열(1번 인덱스)의 150 이상인 행을 출력
print(sales[:, 1] >= 150)
sales[sales[:, 1] >= 150]

[ True False  True False  True]


array([[120, 150, 100],
       [200, 180, 220],
       [300, 320, 310]])