## ndarray 연산

In [1]:
import numpy as np

In [34]:
a = np.arange(1, 10).reshape(3, 3) # 3행 3열
print(a)
# np.arange(1, 10).shape
b = np.full_like(a, 2)
print(b)



[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [15]:
# 덧셈
print(a)
print(b)
print(np.add(a, b))

a + b

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 2 2]
 [2 2 2]
 [2 2 2]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [17]:
# 뺄셈
print(a)
print(b)
print(np.subtract(a, b)) # np.subtrack(a, b) : 두 배열 a와 b의 요소별 뺄셈을 수행
a - b

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 2 2]
 [2 2 2]
 [2 2 2]]
[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]


array([[-1,  0,  1],
       [ 2,  3,  4],
       [ 5,  6,  7]])

In [19]:
# 곱셈
print(np.multiply(a, b))
a * b

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [21]:
# 나누기
print(np.divide(a, b))
a / b

[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]


array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 4. , 4.5]])

In [23]:
# 몫
print(np.floor_divide(a, b))
a // b

[[0 1 1]
 [2 2 3]
 [3 4 4]]


array([[0, 1, 1],
       [2, 2, 3],
       [3, 4, 4]])

In [26]:
# 나머지
print(np.mod(a, b))
a % b

[[1 0 1]
 [0 1 0]
 [1 0 1]]


array([[1, 0, 1],
       [0, 1, 0],
       [1, 0, 1]])

In [36]:
# 거듭제곱
print(np.power(a, b))  # a: 밑, b: 지수
print('===========')
print(np.square(a))

a = [
    [1, 4, 9],
    [16, 25, 36],
    [49, 64, 81]
]
print('===========')
# 제곱근
np.sqrt(a)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

### broadcating 연산
- 두 배열의 shape이 다르면 broadcasting 연산 수행한다.
- shape이 작은 쪽이 큰쪽을 맞춰 확장한다.
- 두 배열의 행 또는 열이 일치해야 확장가능하다.
- 크기가 1인 경우 무조건 확장가능하다.
- shape이 다른 경우 마지막 축부터 차원이 동일한지 비교한다.

In [47]:
a = np.array([
    [1, 4, 9],
    [16, 25, 36],
    [49, 64, 81]
])

In [52]:
# a * 3 # 스칼라값

# a * np.array([3])
# a * np.array([3, 3, 3])
a * np.array([[3, 3, 3], [3, 3, 3], [3, 3, 3]])

array([[  3,  12,  27],
       [ 48,  75, 108],
       [147, 192, 243]])

In [57]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([1, 2, 3])
arr1.shape, arr2.shape

((2, 3), (3,))

In [58]:
arr1 + arr2

array([[2, 4, 6],
       [5, 7, 9]])

In [59]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[1], [2]])
arr1.shape, arr2.shape

((2, 3), (2, 1))

In [60]:
arr1 + arr2

array([[2, 3, 4],
       [6, 7, 8]])

In [62]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([[4], [5], [6]])
arr1.shape, arr2.shape
print(arr1)
print('----------')
print(arr2)

[1 2 3]
----------
[[4]
 [5]
 [6]]


In [63]:
arr1 + arr2

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

In [65]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([1, 2])
arr1.shape, arr2.shape
arr1 + arr2

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [69]:
arr1 = np.array([[0, 0, 0], [1, 1, 1], [2, 2, 2]])
arr2 = np.array([5, 6, 7])
arr1.shape, arr2.shape
arr1 + arr2

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

In [71]:
arr3 = np.array([[1, 2], [3, 4]])
arr4 = np.array([[5], [6]])
arr3.shape, arr4.shape
arr3 + arr4

array([[ 6,  7],
       [ 9, 10]])

In [77]:
arr5 = np.array([[1, 2], [3, 4]])
arr6 = np.array([5, 6])
arr5.shape, arr6.shape
arr5 + arr6

array([[ 6,  8],
       [ 8, 10]])

In [76]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[10], [30], [50]])
a.shape, b.shape
a + b
# a + b

array([[11, 12, 13],
       [34, 35, 36],
       [57, 58, 59]])

## 행렬곱셈 Matrix Multiplication
점곱연산 Dot Product (내적)

두 행렬 A B의 곱셈은 첫번째 행렬 A의 행과 두번째 행렬 B의 열간의 곱셈을 수행한다.

조건
- 첫번째 행렬 A의 열의 수와 두번째 행렬 B의 행의 수가 같아야 한다.
- 연산결과는 (첫번째 행렬 A의 행수, 두번째 행렬 B의 열수) 이다.

In [80]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
# print(arr1 * arr2)
print('-------------')
np.dot(arr1, arr2)

-------------


array([[19, 22],
       [43, 50]])

In [81]:
arr3 = np.array([[1, 2, 3], [4, 5, 6]])
arr4 = np.array([[7, 8], [9, 10], [11, 12]])

arr3.shape, arr4.shape

((2, 3), (3, 2))

In [82]:
np.dot(arr3, arr4)

array([[ 58,  64],
       [139, 154]])

In [83]:
np.dot(arr4, arr3)

array([[ 39,  54,  69],
       [ 49,  68,  87],
       [ 59,  82, 105]])

In [ ]:
# (100, 20000) (100, 20000) # 내적 안됨
# (100, 20000) (20000, 100) # 100, 100
# (20000, 100) (100, 20000) # 20000, 20000

In [85]:
print(arr3 @ arr4)
np.matmul(arr3, arr4)

[[ 58  64]
 [139 154]]


array([[ 58,  64],
       [139, 154]])

In [87]:
# 행렬곱셈을 위해 행렬을 전치할 수 있다.
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
# arr @ arr # ValueError

print(arr.T) # arr 전치행렬 (행/열을 교환)
arr @ arr.T

[[1 4]
 [2 5]
 [3 6]]


In [88]:
# 절대값
arr = np.array([[1, -2], [3, -4]])
np.abs(arr)

array([[1, 2],
       [3, 4]])

In [90]:
# 반올림
arr = np.array([[1.234, 3.567], [7.89, 10.123]])
np.round(arr)
np.round(arr, 2)

array([[ 1.23,  3.57],
       [ 7.89, 10.12]])

In [92]:
# 올림
arr = np.array([[1.234, 3.567], [7.89, 10.123]])
np.ceil(arr)
np.ceil(arr * 10) / 10

array([[ 1.3,  3.6],
       [ 7.9, 10.2]])

In [93]:
# 내림 (지정된 수보다 작은 최대 정수)
arr = np.array([[1.234, -3.456], [-7.89, 10.123]])
np.floor(arr)

array([[ 1., -4.],
       [-8., 10.]])

In [95]:
# 버림 (절삭)
arr = np.array([[1.234, -3.567], [-7.89, 10.123]])
np.trunc(arr)

array([[ 1., -3.],
       [-7., 10.]])

In [100]:
# 최소/최대값
# arr = np.arange(1, 7).reshape(2, 3)
arr = np.array([
    [7, 2, 9],
    [8, 5, 1],
    [8, 6, 4]
])
print(arr)
print(np.min(arr), np.max(arr))


[[7 2 9]
 [8 5 1]
 [8 6 4]]
1 9


In [101]:
np.min(arr, axis=0) # 행기준(행을 고정하고, 같은 열에서 가장 작은 값)

array([7, 2, 1])

In [102]:
np.min(arr, axis=1) # 열기준(열을 고정하고, 같은 행에서 가장 작은 값)

array([2, 1, 4])

In [105]:
arr = np.arange(1, 7).reshape(2, 3)
print(arr.sum()) # axis=None 모든 값에 대해 합을 계산
np.sum(arr)

21


np.int64(21)

In [106]:
arr.sum(axis=0)

array([5, 7, 9])

In [107]:
arr.sum(axis=1)

array([ 6, 15])

In [109]:
# 평균 mean
arr = np.arange(1, 7).reshape(2, 3)
print(arr.mean())
np.mean(arr)

3.5


np.float64(3.5)

In [110]:
arr.mean(axis=0)

array([2.5, 3.5, 4.5])

In [111]:
arr.mean(axis=1)

array([2., 5.])