# ndarray 정렬

## 1차원 배열 정렬

In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1, 11, 10)

arr

array([10,  2,  7,  1,  5,  2,  1,  9,  4,  5], dtype=int32)

In [3]:
# arr.sort() #inplace 연산

arr = np.sort(arr) # 정렬된 새 배열 반환
arr

array([ 1,  1,  2,  2,  4,  5,  5,  7,  9, 10], dtype=int32)

In [4]:
np.sort(arr)[::-1]

array([10,  9,  7,  5,  5,  4,  2,  2,  1,  1], dtype=int32)

## 2차원 배열 정렬

In [13]:
arr = np.random.randint(10, size=(3, 4))
print(arr)
arr.shape

[[6 6 9 6]
 [6 6 6 0]
 [5 2 7 9]]


(3, 4)

In [8]:
# axis=1(기본값) 열방향
np.sort(arr, axis=1)

array([[1, 4, 9, 9],
       [0, 6, 8, 8],
       [2, 8, 9, 9]], dtype=int32)

In [9]:
# axis=0 행방향 (같은 열안에서 정렬)
np.sort(arr, axis=0)

array([[8, 2, 1, 0],
       [9, 6, 8, 4],
       [9, 9, 8, 9]], dtype=int32)

In [11]:
# axis=None 축무시 (행/열 구분없이 모든 값에 대해 정렬)
arr = np.sort(arr, axis=None)

print(arr)
arr.shape

[0 1 2 4 6 8 8 8 9 9 9 9]


(12,)

## np.argsort
배열의 값을 정렬한 후, **정렬된 순서에 해당하는** 인덱스 배열을 반환

In [16]:
arr = np.array([40, 10, 20, 30])
np.sort(arr)
sorted_indices = np.argsort(arr)
arr[sorted_indices]

array([10, 20, 30, 40])

In [20]:
# 우수학생 정렬하기
names = np.array(['홍길동', '신사임당', '이순신','유관순'])
scores = np.array([90, 88, 75, 95])

np.argsort(scores)
scores_desc = np.argsort(scores)[::-1]
names[scores_desc]

array(['유관순', '홍길동', '신사임당', '이순신'], dtype='<U4')

In [25]:
# 2차원배열 argsort
arr = np.array([[3, 1, 7], [6, 4, 5]])
print(arr)
np.argsort(arr, axis=1)


[[3 1 7]
 [6 4 5]]


array([[1, 0, 2],
       [1, 2, 0]])

In [26]:
np.argsort(arr, axis=0)

array([[0, 0, 1],
       [1, 1, 0]])