# ndarray 병합 분할

ndarray는 고정길이의 배열이므로 크기를 변경할 수 없다.

요소를 추가할 수 없다. 추가시에는 길이가 늘어난 새로운 배열을 반환.

## ndarray 요소 추가/삭제

In [3]:
# 파이썬 리스트
lst = [10, 20 ,30]
lst.append(40)
lst.insert(1, 15)
lst

[10, 15, 20, 30, 40]

In [4]:
import numpy as np

In [10]:
arr = np.array([10, 20, 30])
# arr.append(40) #AttributeError: 'numpy.ndarray' object has no attribute 'append'
arr2 = np.insert(arr, 1, 15)
arr2
arr is arr2

False

In [12]:
# 2차원 배열에 요소 추가 insert
arr = np.arange(1, 13).reshape(3, 4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [14]:
np.insert(arr, 3, [10, 20, 30, 40], axis=0)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [17]:
np.insert(arr, 3, [10, 10, 10], axis=1)

np.insert(arr, 3, [10], axis=1)

np.insert(arr, 3, 10, axis=1)

array([[ 1,  2,  3, 10,  4],
       [ 5,  6,  7, 10,  8],
       [ 9, 10, 11, 10, 12]])

In [21]:
# 1차원 배열 delete
arr = np.arange(1, 13)
np.delete(arr, 3)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [22]:
# 2차원 배열 delete
arr = np.arange(1, 13).reshape(3, 4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [23]:
np.delete(arr, 1, axis=0)

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [27]:
np.delete(arr, 2, axis=1)

array([[ 1,  2,  4],
       [ 5,  6,  8],
       [ 9, 10, 12]])

## ndarray 병합
- np.append()
- np.vstack()
- np.hstack()
- np.concatenate()

In [28]:
# np.append()
arr1 = np.arange(1, 13).reshape(3, 4)
arr2 = np.arange(13, 25).reshape(3, 4)
arr1, arr2

(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]))

In [29]:
np.append(arr1, arr2, axis=0)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [30]:
np.append(arr1, arr2, axis=1)

array([[ 1,  2,  3,  4, 13, 14, 15, 16],
       [ 5,  6,  7,  8, 17, 18, 19, 20],
       [ 9, 10, 11, 12, 21, 22, 23, 24]])

In [31]:
# np.vstack() : axis=0 병합
# - list/tuple로 묶어서 전달
arr1 = np.arange(1, 13).reshape(3, 4)
arr2 = np.arange(13, 25).reshape(3, 4)

np.vstack((arr1, arr2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [32]:
# np.hstack() : axis=1 병합
np.hstack((arr1, arr2))

array([[ 1,  2,  3,  4, 13, 14, 15, 16],
       [ 5,  6,  7,  8, 17, 18, 19, 20],
       [ 9, 10, 11, 12, 21, 22, 23, 24]])

In [35]:
# np.concatenate() : axis=0,1,None 병합
# - list/tuple로 묶어서 전달
np.concatenate((arr1, arr2), axis=0)
np.concatenate((arr1, arr2), axis=1)
np.concatenate((arr1, arr2), axis=None)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

## ndarray 분할

In [37]:
# np.split
arr = np.arange(1, 25).reshape(6, 4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [38]:
# 6행의 약수인 1, 2, 3, 6 사용
np.split(arr, 3, axis=0)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]]),
 array([[17, 18, 19, 20],
        [21, 22, 23, 24]])]

In [42]:
np.split(arr, 2, axis=1)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18],
        [21, 22]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16],
        [19, 20],
        [23, 24]])]