# ndarray 형태변경

In [1]:
import numpy as np

In [14]:
# reshape
# 요소의 개수에 맞는 차원으로 변경이 가능하다.
arr = np.arange(12)
print(arr.ndim)
arr = arr.reshape(3, 4)
arr = arr.reshape(6, 2)
arr = arr.reshape(12, 1)
print(arr.ndim)
arr = arr.reshape(2, 2, 3)
print(arr.ndim)


1
2
3


In [20]:
arr = arr.reshape(4, -1) # -1축은 자동계산
arr = arr.reshape(-1, 3)
arr = arr.reshape(-1)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [22]:
# np.ravel() : 1차원 변환
arr = np.arange(50).reshape(5, 10)
arr
np.ravel(arr)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [28]:
# np.expand_dims()
arr = np.array([1, 2])
print(arr)
# arr.shape

[1 2]


In [25]:
print(np.expand_dims(arr, axis=0)) # 행으로 차원추가
print(np.expand_dims(arr, axis=1)) # 열로 차원추가

[[1 2]]
[[1]
 [2]]


In [29]:
# 2차원 -> 3차원 확장
arr = np.array([[1, 2], [3, 4]])
print(arr)

[[1 2]
 [3 4]]


In [32]:
print(np.expand_dims(arr, axis=0))
print(np.expand_dims(arr, axis=1))
print(np.expand_dims(arr, axis=2))

[[[1]
  [2]]

 [[3]
  [4]]]


In [34]:
# np.squeeze() : 차원의 값이 1일때 제거
arr = np.array([[1, 2]])
arr.shape, arr.ndim

((1, 2), 2)

In [38]:
arr2 = np.squeeze(arr, axis=0)
arr2.shape, arr2.ndim

((2,), 1)

In [40]:
arr = np.array([[[1], [2]], [[3], [4]]])
arr.shape, arr.ndim

((2, 2, 1), 3)

In [41]:
arr2 = np.squeeze(arr, axis=2)
arr2.shape, arr2.ndim

((2, 2), 2)